name: Border
version: '${project.version}'
main: jp.houlab.mochidsuki.border.Main
api-version: '1.20'

commands:
  debug:
    aliases: [debug]
    description: BRC管理コマンド
    permission: border.command.debug
    permission-message: Permission denied
    usage: gr reload

  ddamage:
    aliases: [ddamage]
    description: BRC管理コマンド
    permission: border.command.ddamage
    permission-message: Permission denied
    usage: gr reload